server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatxf
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
